name: Build and release Android APK

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: "8"
      - run: yarn --dev --frozen-lockfile
      - run: yarn turtle setup:android
      - run: yarn turtle build:android -t apk --output freecbt.apk | tee build.log
        env:
          EXPO_USERNAME: erosson
          EXPO_PASSWORD: ${{ secrets.EXPO_CLI_PASSWORD }}
          #EXPO_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.EXPO_ANDROID_KEYSTORE_PASSWORD }}
          #EXPO_ANDROID_KEY_PASSWORD: ${{ secrets.EXPO_ANDROID_KEY_PASSWORD }}
      # turtle doesn't have a useful exit code, so fail here if it didn't generate our apk
      - run: test -f freecbt.apk
      # release only for new tags
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            freecbt.apk
