name: Build app, submit to appstores, tag git

on:
  push:
    branches:
      - appstore-build

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22.x
      # https://github.com/expo/expo-github-action
      # using their action logs us in, and avoids ENOSPC: https://github.com/expo/expo-github-action/issues/20
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: erosson
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      - run: yarn --dev --frozen-lockfile
      # TODO: tests temporarily disabled. I have a plan. 2025/10/27
      # - run: yarn test
      # working-directory: expo47
      - run: npm install -g eas-cli # this one doesn't like local installs for some reason

      # submitting builds to the app stores requires some auth files, stored as github secrets
      - run: mkdir -p ./secrets/android ./secrets/ios
      - env:
          EXPO_ANDROID_SERVICE_ACCOUNT_KEY_BASE64: ${{ secrets.EXPO_ANDROID_SERVICE_ACCOUNT_KEY_BASE64 }}
        # path below must match `eas.json:android.serviceAccountKeyPath`
        run: |
          echo $EXPO_ANDROID_SERVICE_ACCOUNT_KEY_BASE64 | base64 --ignore-garbage --decode > ./secrets/android/api-8973054243569294648-99738-365ad35f4cc4.json
      - env:
          EXPO_IOS_API_KEY_BASE64: ${{ secrets.EXPO_IOS_API_KEY_BASE64 }}
        # path below must match `eas.json:ios.ascApiKeyPath`
        run: |
          echo $EXPO_IOS_API_KEY_BASE64 | base64 --ignore-garbage --decode > ./secrets/ios/AuthKey_DLK4FD42VZ.p8
      - run: cat ./secrets/android/*.json
      - run: cat ./secrets/ios/*.p8

      - run: yarn appstore-build
        working-directory: expo47
